spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medic_bridge_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # debug: create / update / create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

application:
  client:
    url: "http://localhost:4200"
  server:
    url: "http://localhost:8080"
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs