spring:
#  config:
#    activate:
#      on-profile: local //todo later on prod/test/local smart swap
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${MB_AWS_ACCESS_KEY}
        secret-key: ${MB_AWS_SECRET_KEY}
      s3:
        endpoint: ${MB_AWS_ENDPOINT}
        path-style-access-enabled: true
  datasource:
    url: ${MB_DB_URL}
    username: ${MB_DB_USERNAME}
    password: ${MB_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # debug: create / update / create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CMS_EMAIL_USER}
    password: ${CMS_EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

application:
  client:
    url: "http://localhost:4200"
  server:
    url: "http://localhost:8080"
  security:
    jwt:
      secret-key: ${MB_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

file:
  upload-dir: ${FILE_UPLOAD_DIR}

